version: '2.1'

services:
  fortune:
    container_name: fortune
    build:
      context: .
      dockerfile: ./docker/net-fortune/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: fortune-db
    build:
      context: ./docker/net-fortune-db/
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
          test: exit 0
    environment:
      POSTGRES_DB: fortunedb
      POSTGRES_USER: mister
      POSTGRES_PASSWORD: 'default_password'


